spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/C_sharing?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Howard0415
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    com.lrm: debug
  file:
    path: log/my.log
